version: "3"
services:
  app:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: "mongodb://mongo:27017/any-shop-test"
      PORT: 3000
  mongo:
    image: mongo:4.2-bionic

    expose:
      - 27017
